kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-store
mountOptions:
  - vers=4.1
reclaimPolicy: Retain 
volumeBindingMode: Immediate
